// Emit a TypeScript declaration file describing the entity meta shape for
// each registered schema. The generated file is plain text — we don't
// invoke the TypeScript compiler — so consumers don't need tsc installed.
//
// The shape is:
//
//   import type { z } from 'zod'
//   import articleSchema from './schemas/article.js'
//   import productSchema from './schemas/product.js'
//
//   export type ArticleMeta = z.infer<typeof articleSchema>
//   export type ProductMeta = z.infer<typeof productSchema>
//
//   export interface LayoutMap {
//       article: ArticleMeta
//       product: ProductMeta
//   }
//
//   export type LayoutName = keyof LayoutMap
//   export type MetaByLayout<L extends LayoutName> = LayoutMap[L]
//
// SDK consumers can then write:
//
//   import type { MetaByLayout } from './entities'
//   const { document } = useDocument<{ meta: MetaByLayout<'article'> }>(id)
//
// or build a discriminated union over layouts for narrow typing.

import path from 'node:path'
import { writeFile, mkdir } from 'node:fs/promises'

function pascalCase(name) {
    return name
        .split(/[-_/.]+/)
        .filter(Boolean)
        .map(part => part[0].toUpperCase() + part.slice(1))
        .join('')
}

/**
 * Write the .d.ts to `outputPath` based on the loaded schemas.
 *
 * @param {object} opts
 * @param {Record<string, { name: string, source: string }>} opts.schemas
 *   Map of layout name → { name, source } (source is the absolute path to
 *   the schema module, used to compute a relative import).
 * @param {string} opts.outputPath  Absolute path to the .d.ts target.
 */
export async function writeTypes({ schemas, outputPath }) {
    await mkdir(path.dirname(outputPath), { recursive: true })

    const entries = Object.entries(schemas).sort(([a], [b]) => a.localeCompare(b))
    if (entries.length === 0) {
        // Still emit something so downstream type-checking doesn't break
        // when the project is mid-migration with zero schemas yet.
        const empty = [
            '// Generated by mikser-io-schemas. Do not edit by hand.',
            '',
            'export interface LayoutMap {}',
            'export type LayoutName = keyof LayoutMap',
            'export type MetaByLayout<L extends LayoutName> = LayoutMap[L]',
            '',
        ].join('\n')
        await writeFile(outputPath, empty, 'utf8')
        return
    }

    const outDir = path.dirname(outputPath)
    const imports = []
    const typeAliases = []
    const mapLines = []

    for (const [layout, { source }] of entries) {
        const ident = `${pascalCase(layout)}Schema`
        const metaAlias = `${pascalCase(layout)}Meta`
        let importPath = path.relative(outDir, source).replace(/\\/g, '/')
        if (!importPath.startsWith('.')) importPath = `./${importPath}`

        imports.push(`import ${ident} from '${importPath}'`)
        typeAliases.push(`export type ${metaAlias} = z.infer<typeof ${ident}>`)
        mapLines.push(`    '${layout}': ${metaAlias}`)
    }

    const body = [
        '// Generated by mikser-io-schemas. Do not edit by hand.',
        '',
        "import type { z } from 'zod'",
        ...imports,
        '',
        ...typeAliases,
        '',
        'export interface LayoutMap {',
        ...mapLines,
        '}',
        '',
        'export type LayoutName = keyof LayoutMap',
        'export type MetaByLayout<L extends LayoutName> = LayoutMap[L]',
        '',
    ].join('\n')

    await writeFile(outputPath, body, 'utf8')
}
